config/routes.rb
Rails.application.routes.draw do
  # get 'users/show'
  # devise_for :users
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Redirect login to root_path
  namespace :users do
    redirect to: 'movie#index'
  end
  get 'movies/voting', to: 'movies#votes'
  get 'movies/title', to: 'movies#title'

  root 'movies#index'

  resources :users, only: %i[show index] do
    resources :watch_lists
  end
  resources :watch_lists

  resources :movies

end

app/controllers/movies_controller.rb
require 'pry'

class MoviesController < ApplicationController
  include MoviesHelper

  def index
    movie_popular(1)
    @movies = Movie.all
    @featured_movie = @movies.sample
    @movies_vote = Movie.all.voting
  end

  def show
    @movie = Movie.find(params[:id])
    loc_movie = @movie.movie_id
    movie_detail(loc_movie)
  end

  def votes
    @movies = Movie.all.voting
  end

  def title
    @movies = Movie.all.title
  end

end

app/helpers/movies_helper.rb
module MoviesHelper

  # TODO: Migrate to rails credentials
  def movie_popular(page)
    data = JSON.parse(RestClient.get("https://api.themoviedb.org/3/movie/popular?api_key=#{ENV['MOVIE_API']}&page=#{page.to_s}"))
    data['results'].each do |movie|
      existing_movies = Movie.find_by(movie_id: movie['id'])
      next if existing_movies

      new_movie = Movie.new do |m|
        m.movie_id = movie['id']
        m.title = movie['title']
        m.release_date = movie['release_date']
        m.poster_path = movie['poster_path']
        m.backdrop_path = movie['backdrop_path']
        m.overview = movie['overview']
        m.average_vote = movie['vote_average']
      end
      new_movie.save
    end
  end

  def movie_detail(loc_movie)
    detail_data = JSON.parse(RestClient.get("https://api.themoviedb.org/3/movie/#{loc_movie}?api_key=#{ENV['MOVIE_API']}"))
    edit_movie = Movie.find_by(movie_id: loc_movie)
    edit_movie.budget = detail_data['budget']
    edit_movie.tagline = detail_data['tagline']
    edit_movie.runtime = detail_data['runtime']
    edit_movie.save
  end
end

app/views/movies/index.html.erb
<main class="my-background-cover">
  <div class="container mx-auto py-5">

    <div class="py-8 text-center">
      <h1 class="text-5xl text-yellow-500 font-bold mb-2">Movie Portal</h1>
      <p class="text-xl text-yellow-500 font-bold mb-8">❤️ Your entertainment planner ❤️</p>
    </div>

    <div class="my-5 mx-auto text-center">
      <button class="btn bg-yellow-500 hover:bg-yellow-700">
          <%= link_to "Popular", root_path %>
      </button>
      <button class="btn bg-transparent border border-yellow-500 hover:border-transparent hover:bg-yellow-700">
        <%= link_to "Top Reviewed", movies_voting_path %>
      </button>
      <button class="btn bg-transparent border border-yellow-500 hover:border-transparent hover:bg-yellow-700">
        <%= link_to "Ascending", movies_title_path %>
      </button>
    </div>
    
    <% if @movies %>
      <div class="flex flex-wrap overflow-hidden justify-center">
        <% @movies.each do |movie| %>
          <div class="overflow-hidden rounded shadow-lg w-48 bg-black m-5">
            <div class="bg-cover bg-center w-48 h-auto">
              <%= link_to (image_tag 'https://image.tmdb.org/t/p/w300/' + movie.poster_path), movie_path(movie.id) %>
            </div>
            <div class="inline-flex justify-between space-between w-48 p-2">
              <div class="text-white text-lg"><%= movie.title %></div>
              <div class="card-rating pr-4"><%= movie.average_vote %></div>
            </div>
          </div>
        <% end %>
      </div>

    <% end %>
  </div>

</main>

app/views/movies/show.html.erb
<main style="background-image: url(<%= 'https://image.tmdb.org/t/p/w1280/' + @movie.backdrop_path %>);"
      class="min-h-screen min-w-screen bg-fixed bg-cover bg-no-repeat">

  <div class="container mx-auto p-5">
    <div class="movie h-auto">
      <%= image_tag 'https://image.tmdb.org/t/p/w300/' + @movie.poster_path %>
      <div class="p-5">
        <h2 class="text-yellow-500 text-4xl font-medium mb-2"><%= @movie.title %></h2>
        <p class="text-xl mb-4"><%= @movie.tagline %></p>
        <% if user_signed_in? %>
          <button class="bg-green-500 hover:bg-green-700 mb-5">
            <%= link_to "Add to Watchlist", edit_user_watch_list_path(movie_id: @movie, user_id: current_user[:id]) %>
          </button>
          <% else %>
          <button class="bg-green-500 hover:bg-green-700 mb-5">Log in to create a watchlist</button>
          <% end %>
        <div class="movie__rating text-white"><%= @movie.average_vote %></div>
        <p class="text-xl font-light mb-5"><%= @movie.overview %></p>
      </div>
      <div class="movie__stat inline-flex justify-between items-center">
        <div>
          <p>
            <i class="far fa-clock text-2xl mr-3 pt-1"></i>
            Release Date: <%= (@movie.release_date).to_time.strftime(' %b %d %Y') %></p>
        </div>
        <div>
          <p><i class="fas fa-history text-2xl mr-3 pt-1"></i>Duration: <%= @movie.runtime %>m</p>
        </div>
        <div>

          <p><i class="far fa-money-bill-alt text-2xl mr-3 pt-1"></i>Budget:
            <% if @movie.budget != 0 %>
              <%= number_to_currency(@movie.budget, unit: '$', precision: 0) %>
            <% else %>
              N/A
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/movies/title.html.erb
<main class="my-background-cover">
  <div class="container mx-auto py-5">

    <div class="py-8 text-center">
      <h1 class="text-5xl text-yellow-500 font-bold mb-2">Movie Portal</h1>
      <p class="text-xl text-yellow-500 font-bold mb-8">❤️ Your entertainment planner ❤️</p>
    </div>

    <div class="my-5 mx-auto text-center">
      <button class="btn bg-transparent border border-yellow-500 hover:border-transparent hover:bg-yellow-700">
        <%= link_to "Popular", root_path %>
      </button>
      <button class="btn bg-transparent border border-yellow-500 hover:border-transparent hover:bg-yellow-700">
        <%= link_to "Top Reviewed", movies_voting_path %>
      </button>
      <button class="btn bg-yellow-500 hover:bg-yellow-700">
        <%= link_to "Ascending", movies_title_path %>
      </button>
    </div>

    <% if @movies %>
      <div class="flex flex-wrap overflow-hidden justify-center">
        <% @movies.each do |movie| %>
          <div class="overflow-hidden rounded shadow-lg w-48 bg-black m-5">
            <div class="bg-cover bg-center w-48 h-auto">
              <%= link_to (image_tag 'https://image.tmdb.org/t/p/w300/' + movie.poster_path), movie_path(movie.id) %>
            </div>
            <div class="inline-flex justify-between space-between w-48 p-2">
              <div class="text-white text-lg"><%= movie.title %></div>
              <div class="card-rating pr-4"><%= movie.average_vote %></div>
            </div>
          </div>
        <% end %>
      </div>

    <% end %>
  </div>

</main>

app/views/movies/votes.html.erb
<main class="my-background-cover">
  <div class="container mx-auto py-5">

    <div class="py-8 text-center">
      <h1 class="text-5xl text-yellow-500 font-bold mb-2">Movie Portal</h1>
      <p class="text-xl text-yellow-500 font-bold mb-8">❤️ Your entertainment planner ❤️</p>
    </div>

    <div class="my-5 mx-auto text-center">
      <button class="btn bg-transparent border border-yellow-500 hover:border-transparent hover:bg-yellow-700">
        <%= link_to "Popular", root_path %>
      </button>
      <button class="btn bg-yellow-500 hover:bg-yellow-700">
        <%= link_to "Top Reviewed", movies_voting_path %>
      </button>
      <button class="btn bg-transparent border border-yellow-500 hover:border-transparent hover:bg-yellow-700">
        <%= link_to "Ascending", movies_title_path %>
      </button>
    </div>

    <% if @movies %>
      <div class="flex flex-wrap overflow-hidden justify-center">
        <% @movies.each do |movie| %>
          <div class="overflow-hidden rounded shadow-lg w-48 bg-black m-5">
            <div class="bg-cover bg-center w-48 h-auto">
              <%= link_to (image_tag 'https://image.tmdb.org/t/p/w300/' + movie.poster_path), movie_path(movie.id) %>
            </div>
            <div class="inline-flex justify-between space-between w-48 p-2">
              <div class="text-white text-lg"><%= movie.title %></div>
              <div class="card-rating pr-4"><%= movie.average_vote %></div>
            </div>
          </div>
        <% end %>
      </div>

    <% end %>
  </div>

</main>