config/routes.rb
Rails.application.routes.draw do
  # get 'users/show'
  # devise_for :users
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Redirect login to root_path
  namespace :users do
    redirect to: 'movie#index'
  end
  get 'movies/voting', to: 'movies#votes'
  get 'movies/title', to: 'movies#title'

  root 'movies#index'

  resources :users, only: %i[show index] do
    resources :watch_lists
  end
  resources :watch_lists

  resources :movies

end

app/models/watch_list.rb
class WatchList < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  accepts_nested_attributes_for :movie
end

app/controllers/watch_lists_controller.rb
class WatchListsController < ApplicationController
  skip_before_action :verify_authenticity_token
  include MoviesHelper

  def index
    @user_list = WatchList.where(user_id: current_user[:id])
  end

  def show
    @movie = Movie.find(params[:id])
    loc_movie = @movie.movie_id
    movie_detail(loc_movie)
  end

  def edit
    @movie = Movie.find(params[:id])
    @watch_list = WatchList.find_by_movie_id(params[:id])
    if @watch_list.nil?
      @watch_list = WatchList.new do |m|
        m.user_id = current_user['id']
        m.movie_id = @movie['id']
        m.movie_title = @movie['title']
        m.poster_path = @movie['poster_path']
      end
      @watch_list.save!
      flash[:notice] = 'Your selection has been added to your watchlist.'
    end
  end

  def update
    @watch_list = WatchList.find(params[:id])
    if @watch_list.update(watch_list_params)
      redirect_to user_watch_lists_path(current_user), notice: 'Your comment has been saved to your watchlist.'
    end
  end

  def destroy
    @watch_list = WatchList.find_by_movie_id(params[:id])
    @watch_list.destroy
    redirect_to watch_lists_path
    flash[:notice] = 'Your movie has been deleted from your watchlist.'
  end

  private

  def watch_list_params
    params.require(:watch_list).permit(
      :user_id,
      :movie_id,
      :movie_title,
      :poster_path,
      :comments
    )
  end

end

app/views/watch_lists/delete.html.erb
<h1>WatchLists#delete</h1>
<p>Find me in app/views/watch_lists/delete.html.erb</p>

app/views/watch_lists/edit.html.erb
<main style="background-image: url(<%= 'https://image.tmdb.org/t/p/w1280/' + @movie.backdrop_path %>);" class="min-h-screen min-w-screen bg-fixed bg-cover bg-no-repeat">
  <div class="w-full max-w-sm mx-auto pt-8">
    <%= form_for(@watch_list, html: { class: "card opacity-75" }) do |f| %>
      <span class="text-2xl text-bold mb-2">Edit Movie</span>
      <hr class="border-b-4 w-3/4 border-teal-500 mb-3">
      <%= f.label :movie_id, 'Movie ID', class: "font-bold text-lg my-5 px-2 py-2" %>: <%= @movie.movie_id %><br/>
      <%= f.label :title, 'Movie Title', class: "font-bold text-lg my-5 px-2 py-2" %>: <%= @movie.title %><br/>
      <%= f.label :title, 'My Comments', class: "font-bold text-lg my-5 px-2 py-2" %>:<br/>
      <%= f.text_area(:comments, size: '30x10', class: "user-form-field py-2 px-3 mb-3") %>
      <%= f.submit 'Save', class: "bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 mb-4 rounded focus:outline-none focus:shadow-outline" %>
    <% end %>
    <p class="text-center text-gray-200 text-xs">
      &copy;2019 EclecticCoding. All rights reserved.
    </p>
  </div>
</main>

app/views/watch_lists/index.html.erb
<main class="my-background-cover min-h-screen">
  <div class="container w-1/2 card mx-auto py-15 pt-10">
    <span class="text-2xl text-bold mb-2">Your WatchList</span>
    <hr class="border-b-4 w-3/4 border-teal-500 mb-3">
    <% if @user_list.empty? %>
      <p>No WatchList found</p>
      <p>After you add a movie to a watch list, you may view it here.</p>
      <p class="mt-5">
        <button><%= link_to "Back to Movies List", root_path, class: "bg-green-500 hover:bg-green-700 mt-8 mb-5 py-3 px-4 rounded-lg font-bold cursor-pointer" %></button>
      </p>
    <% else %>
      <table class="table">
        <thead>

        <tr>
          <th class="w-1/4 px-4 py-2">Image</th>
          <th class="w-1/4 px-4 py-2">Movie Title</th>
          <th class="w-1/4 px-4 py-2">My Comments</th>
        </tr>
        </thead>
        <tbody>
        <% @user_list.each do |list| %>
          <tr>
            <td class="border px-4 py-2"><%= image_tag 'https://image.tmdb.org/t/p/w92/' + list.poster_path %></td>
            <td class="border px-4 py-2"><%= link_to list.movie_title, watch_list_url(list.movie_id), class: "text-red-600 hover:text-red-800 font-bold" %></td>
            <td class="border px-4 py-2"><%= list.comments %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <div class="mt-5">
        <button><%= link_to "Back to Movies List", root_path, class: "bg-green-500 hover:bg-green-700mb-5 py-3 px-4 rounded-lg font-bold cursor-pointer" %></button>
      </div>
    <% end %>
  </div>
</main>

app/views/watch_lists/show.html.erb
<main style="background-image: url(<%= 'https://image.tmdb.org/t/p/w1280/' + @movie.backdrop_path %>);"
      class="min-h-screen min-w-screen bg-fixed bg-cover bg-no-repeat">

  <div class="container mx-auto p-5">
    <div class="movie h-auto">
      <%= image_tag 'https://image.tmdb.org/t/p/w300/' + @movie.poster_path %>
      <div class="p-5">
        <h2 class="text-yellow-500 text-4xl font-medium mb-2"><%= @movie.title %></h2>
        <p class="text-xl mb-4"><%= @movie.tagline %></p>
        <div class="flex">
          <button class="bg-green-500 hover:bg-green-700 mb-5">
            <%= link_to "Edit Watchlist", edit_user_watch_list_path(movie_id: @movie, user_id: current_user[:id]), class: "bg-green-500 hover:bg-green-700 mb-5 py-3 rounded-lg font-bold cursor-pointer" %>
          </button>
          <%= button_to 'Delete', watch_list_path, method: :delete, class: "bg-green-500 hover:bg-green-700 mb-5 py-3 px-4 rounded-lg font-bold cursor-pointer" %>
        </div>
        <div class="movie__rating text-white"><%= @movie.average_vote %></div>
        <p class="text-xl font-light mb-5"><%= @movie.overview %></p>
      </div>
      <div class="movie__stat inline-flex justify-between items-center">
        <div>
          <p>
            <i class="far fa-clock text-2xl mr-3 pt-1"></i>
            Release Date: <%= (@movie.release_date).to_time.strftime(' %b %d %Y') %></p>
        </div>
        <div>
          <p><i class="fas fa-history text-2xl mr-3 pt-1"></i>Duration: <%= @movie.runtime %>m</p>
        </div>
        <div>

          <p><i class="far fa-money-bill-alt text-2xl mr-3 pt-1"></i>Budget:
            <% if @movie.budget != 0 %>
              <%= number_to_currency(@movie.budget, unit: '$', precision: 0) %>
            <% else %>
              N/A
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
</main>