config/routes.rb
Rails.application.routes.draw do
  # get 'users/show'
  # devise_for :users
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Redirect login to root_path
  namespace :users do
    redirect to: 'movie#index'
  end
  get 'movies/voting', to: 'movies#votes'
  get 'movies/title', to: 'movies#title'

  root 'movies#index'

  resources :users, only: %i[show index] do
    resources :watch_lists
  end
  resources :watch_lists

  resources :movies

end

app/views/layouts/_nav.html.erb
<header class="lg:px-16 px-6 bg-black flex flex-wrap items-center lg:py-0 py-2">
  <div class="flex-1 flex justify-between items-center">
    <%= link_to root_path do %>
      <h2 class="text-yellow-500 bold">Movie Portal</h2>
<!--      <svg class="bg-white" width="32" height="36" viewBox="0 0 32 36" xmlns="http://www.w3.org/2000/svg">-->
<!--        <img src="../images/logo.svg" alt="">-->
<!--      </svg>-->
      
    <% end %>
  </div>

  <label for="menu-toggle" class="pointer-cursor lg:hidden block">
    <svg class="fill-current text-gray-100" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20">
      <title>menu</title>
      <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path>
    </svg>
  </label>
  <input class="hidden" type="checkbox" id="menu-toggle"/>

  <div class="hidden lg:flex lg:items-center lg:w-auto w-full" id="menu">
    <nav>
      <ul class="lg:flex items-center justify-between text-base text-gray-200 pt-4 lg:pt-0">
        <% if !user_signed_in? %>
          <li class="lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-indigo-400">
            <%= link_to "Login", new_user_session_path %>
          </li>
          <li class="lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-indigo-400">
            <%= link_to "Signup", new_user_registration_path %>
          </li>
        <% else %>
          <li class="lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-indigo-400">
            <%= link_to "My Watchlist", user_watch_lists_path(current_user)  %>
          </li>
          <li class="lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-indigo-400">
            <%= link_to "Edit Profile", users_path %>
          </li>
          <li class="lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-indigo-400">
            <%= link_to "Logout", destroy_user_session_path %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMovieBrowser</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<!--Image by <a href="https://pixabay.com/users/geralt-9301/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=4430788">Gerd Altmann</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=4430788">Pixabay</a>-->

<body class="min-h-screen bg-gray-400">
<%= render 'layouts/nav' %>

<% flash.keys.each do |type| %>
  <div class="<%= type %>">
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
    <strong><%= flash[type] %></strong>
  </div>
<% end %>

<%= yield %>

</body>

</html>